###
GET http://localhost:8080/api/routes



### Create a route ###
POST http://localhost:8080/api/routes
Content-Type: application/json

{
    "Name": "Route 1",
    "Source": {
        "Name": "Source 1",
        "Latitude": 1.0,
        "Longitude": 1.0
    },
    },
    "Destination": {}
}

