FROM golang:1.17

WORKDIR /app

COPY api /app

RUN go get github.com/pressly/goose/v3/cmd/goose
RUN go get github.com/go-chi/chi
RUN go get github.com/go-sql-driver/mysql

CMD ["go", "run", "main.go"]
